#!/bin/bash

# Generate PR description from commit range
# Usage: ./generate-pr-description.sh <base-sha> [output-file]

set -e

if [ $# -lt 1 ]; then
    echo "Usage: $0 <base-sha> [output-file]"
    echo "Example: $0 8a4adf3d50a9c000029508756cc7ddc0c1dc49af pr-description.md"
    exit 1
fi

BASE_SHA="$1"
OUTPUT_FILE="${2:-pr-description.md}"

echo "Generating PR description from $BASE_SHA to HEAD..."

# Create temporary files
COMMITS_FILE=$(mktemp)
FILES_FILE=$(mktemp)

# Extract commit messages with full bodies
echo "📝 Extracting commit messages..."
git log --pretty=format:"%H%n%s%n%n%b%n---" "$BASE_SHA..HEAD" > "$COMMITS_FILE"

# Get affected files
echo "📁 Getting affected files..."
git diff --name-only "$BASE_SHA..HEAD" > "$FILES_FILE"

# Count commits
COMMIT_COUNT=$(git rev-list --count "$BASE_SHA..HEAD")

# Generate the PR description
cat > "$OUTPUT_FILE" << EOF
# Pull Request: Merge $COMMIT_COUNT commits from klutometis/workshops

## Summary

This PR merges $COMMIT_COUNT commits from the klutometis/workshops fork, preserving the complete commit history and individual contributions.

## Commit Range
- **Base**: \`$BASE_SHA\`
- **Head**: \`$(git rev-parse HEAD)\`
- **Commits**: $COMMIT_COUNT

## Files Changed ($(wc -l < "$FILES_FILE"))

\`\`\`
$(cat "$FILES_FILE")
\`\`\`

## Detailed Commit History

\`\`\`
$(cat "$COMMITS_FILE")
\`\`\`

---
*Generated by tools/generate-pr-description.sh*
EOF

# Count files before cleanup
FILE_COUNT=$(wc -l < "$FILES_FILE")

# Cleanup
rm "$COMMITS_FILE" "$FILES_FILE"

echo "✅ PR description generated: $OUTPUT_FILE"
echo "📊 Summary: $COMMIT_COUNT commits affecting $FILE_COUNT files"
